version: '3.6'

services:

  postgres:
    build:
      context: .
      dockerfile: db/Dockerfile
    env_file: dev.env
    ports:
      - "5432:5432"
    networks:
      - default
    volumes:
      - ../pgdata:/var/lib/postgresql/data
      - ./db/initdb:/docker-entrypoint-initdb.d

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
      args:
        PROJECT_NAME: $PROJECT_NAME
    env_file: dev.env
    depends_on:
      - postgres
    networks:
      - default
    ports:
      - "5000:5000"
    volumes:
      - ..:/$PROJECT_NAME
    environment:
      - PGHOST=postgres
      - PGPORT=5432

  adminer:
    image: adminer
    networks:
      - default
    ports:
      - 8080:8080
    environment:
      - ADMINER_DEFAULT_SERVER=postgres

networks:
  default:
    name: $PROJECT_NAME
