version: 0.2

env:
  shell: bash
  variables:
    HUSKY_SKIP_INSTALL: 1

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install
      - npm run postinstall
  pre_build:
    commands:
#      - npm test test

  build:
    commands:
      - echo Deploy started on `date`
      - npm run build:all
      - npm run prepare:deploy:ci
      - cd packages/titus-infra-aws-mira && npx mira deploy --env=$ENVIRONMENT --file=cdk/index.js --require-approval=never
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files: '**/*'
