version: 0.2

env:
  shell: bash
  variables:
    HUSKY_SKIP_INSTALL: 1

phases:
  install:
    runtime-versions:
      docker: 19
      nodejs: 12
    commands:
      - npm install
      - npm run postinstall
  pre_build:
    commands:
      - echo "REACT_APP_AUTH_PROVIDER=AWS" > packages/titus-frontend/.env
      - echo "REACT_APP_REMOTE_AWS_CONFIG_PATH=/config/v1" >> packages/titus-frontend/.env
      - npm run build:all
      - npm test test
  build:
    commands:
      - echo Deploy started on `date`
      - ./packages/titus-infra-aws-mira/pipeline/pipeline.sh checkEnvironement
      - ./packages/titus-infra-aws-mira/pipeline/pipeline.sh prepareCredentials
      - npm run prepare:deploy:ci
      - ./packages/titus-infra-aws-mira/pipeline/pipeline.sh buildAndPushDockerImage
      - cd packages/titus-infra-aws-mira && NODE_ENV=$ENVIRONMENT npx mira deploy --env=$ENVIRONMENT --file=cdk/index.js --role $ROLE_ARN --require-approval=never
      - ./packages/titus-infra-aws-mira/pipeline/pipeline.sh refreshFargate
      - ./packages/titus-infra-aws-mira/pipeline/pipeline.sh cleanupCredentials
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files: '**/*'
